// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wyvmguyflgdfybyczrue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5dm1ndXlmbGdkZnlieWN6cnVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNTUwNTYsImV4cCI6MjA2NDYzMTA1Nn0.qnb26iXZ28gXOR73284Aj6BhNnmky8aSK5xy0EpaNxg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);